### ISSUE TITLE
As a developer I want to understand what an item is

### ISSUE THREAD

**Issue by c-w** [yunity/yunity#5]

**Comment by c-w** [comment]
In conversation with @valeriko and @Sliverriver, we came up with the following proposal for representing items in the yunity database.

![yuntiy-item-database-schema](https://cloud.githubusercontent.com/assets/1086421/10119918/849f4078-64a5-11e5-8f8e-1af3d289b910.png)

Using this representation, we can cater for everything we want to display on the map: food baskets, places to pick up food, events, car sharing, couch surfing, tools, people sharing skills, etc.

**Comment by maackle** [comment]
I'm confused about the diamond shapes between Mappable and most other tables. Are they join tables in many-to-many relationships?

**Comment by amosgroth** [comment]
Me too. What do they mean?

**Comment by c-w** [comment]
@maackle, @amosgroth 

The shapes come from the world of [ER diagrams](https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model):
- rectangles are entities: things in the database, represented by a table
- diamonds are relations: how the things relate, represented by a table connecting entity tables
- circles are attributes of entities: properties of the things in the database, represented by columns

**Comment by c-w** [comment]
More concretely, the diagram states that we have a mappable thing that has:
- A *name* that the user can provide, describing in short "what is the thing".
- A *provenance*, answering "where did the data come from", e.g. yunity.com if the item was created on our site, or "couchsurfing.com" if we integrate in the future with that site and import all their sharing data into ours.
- A *createdAt* time-stamp showing when the item was created in our system.
- Some *media* like photos or videos that the user can upload to describe the Mappable.
- One or more *owners* of the Mappable which are users in our system. For things like food-baskets, we only need a single owner, but for things like Betrieb in the current food-sharing application, we need multiple owners to represent all the people managing the group that arranges pick-ups from this shop.
- One or more *contacts* which are ways to contact the owner(s) of the item to request more information, e.g. about "how to pick up the food-basket" or "when would be a good time to meet to share your language skill". 
- Zero or *metadatas*. A meta-data is just some key-value pair. E.g. for a food-basket, we could have the mapping "weight -> 5kg". We can use the meta-data map to store any information that is specific to a particular category. We can represent this as a separate table as in this diagram or even just as a JSONP field if Django has good support for that data-type.
- Zero or more *locations*. Locations are represented by GIS coordinates but can optionally be time-limited: "you can pick up this tool from me on Tuesdays at my work between 9am and 5pm or on Thursdays at my home between 10am and 11am".
- Zero or one *antecedents*. This is another Mappable. We use a chain of antecedents to represent the history of the Mappable. For example, imagine that Michael has a hammer that he wants to share. Amos takes the hammer off of Michael so we create a new Mappable that is a copy of Michael's Mappable only with the owner and location information updated and with the antecedent set to Michael's Mappable. In this way, we can build up a chain of how the Mappable moved in between users. Similarly, we can use the antecedent relation to build up an edit trail of ever Mappable, e.g. to represent location changes of the item. If the Mappable is new, i.e. without history, we simply represent this by having no Mappable as antecedent (like a NULL node in a linked list to mark the start).
- One or more *categories*. At first, we seed the categories table with high level entries corresponding to the main circles on yunity: "food-sharing", "car-sharing", "tool-sharing", etc. We also give the user the option to add more fine-grained categories to the items on creation. This should be free-text but encouraging the user to re-use existing categories, e.g. via auto-complete. Every now and then, we should go through all the user-created categories and consolidate them somehow, e.g. by using an ontology or manually. In this way, we build up a tree of categories: "a banana is a fruit is a food" so that we can have a very rich ecosystem of categories that allow us to make fine-grained searches.

Errors in the diagram:
- There's a diamond missing on the arrow connecting the Mappable to the Metadata.
- The arrow on the antecedent relation should be "zero or one", not "exactly one".

Notes:
- This diagram is not an exhaustive schema of all the stuff in our database. For example, the "calendar/responsibility-sharing" widget on the existing shop-pages, we'd have a relation with date/responsibility-name attributes that relates users to the Mappable.
- If we add a "modification-type" field to the antecedent relation, we can implement a full data-vault model for our data-base. We never delete or modify data, we always make a copy and relate the new item to the old item and put a "deprecated" flag on the old item. In this way, we get a full audit trail of everything that happens in our data. This increases our storage but on-disk compression should take care of the bulk of that.

**Comment by c-w** [comment]
![yunity](https://cloud.githubusercontent.com/assets/1086421/10134058/2279d5b8-65e3-11e5-9820-67d6691a0fa5.png)

**Comment by valeriko** [comment]
Looks good.

Shouldn't the location be «one or more» relationship instead of «zero or more»? Items, events, skills, cars — they all have a location, and after all, the name is <i>Map</i>Item.

And maybe we need an additional description, when the new mapitem is going to be created (in sense of history). I mean:
* Amos got a hammer from Michael: create new item;
* Amos got a banana from Michael: do nothing;
* Amos got two bananas from Michael and shares one: create new item (or just change the responsible user?).
