### ISSUE TITLE
Update README's to point to wiki setup instructions

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity#6]
I guess each repo should have a bit of info about what it is, but redirect to the wiki for setup instructions.

**Comment by kkampardi** [comment]
can i start with this one?

**Comment by nicksellen** [comment]
Yes, please do :)

Just check enough of the useful information from the README.md is on the wiki.

**Comment by nicksellen** [comment]
Also, if you can work via fork/pull-request that seems best for now

**Comment by kkampardi** [comment]
Ok i forked the yunity-setup and i'm trying a new setup on my laptop
(i'm experiencing some node issues at the moment, i hope to resolve them soon). Is that right?
Would you be able to share a link the README.md is on the wiki?

**Comment by nicksellen** [comment]
I'm not sure I understand, this task is to update the README.md to point to the wiki, instead of duplicating the setup instructions. The wiki is the main place for them.
