### ISSUE TITLE
Switch to html5 mode urls

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity#7]
html5 mode makes nice urls, it needs a couple of things though:

A) switch angularjs to use html5 urls

This gets added to routes:

```javascript
$locationProvider.html5Mode(true);
```

B) configure proxy.js/webpack to serve up index.html for the valid routes
(ideally can export the actual routes from angular, but otherwise just _unknown routes with no extension_ might be good enough)

C) work out how to do the same for django

**Comment by tiltec** [comment]
Close this? @nicksellen
