### ISSUE TITLE
Merge yunity repositories

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity#9]
Keep maintenance simple, have one place where things happen in regard to foodsaving tool
- [x] Rename to foodsaving
- [x] Archive setup repository
- [ ] Merge foodsaving-socket into foodsaving-backend

Merge proj1 into proj2

```
# in proj2:
git remote add proj1 path/to/proj1
git fetch proj1
git merge proj1/master # or whichever branch you want to merge
```

https://stackoverflow.com/questions/2949738/git-merge-different-repositories

**Comment by nicksellen** [comment]
I think this is a good idea. it slightly goes against the _plurality of frontends_ approach, but I think focusing on one is more practical.

maybe point 4 could be rename `yunity-core` into `foodsharing-international`?

I wonder if we could replace `yunity-sockets` with something in python now too, given https://github.com/aaugustin/websockets

**Comment by nicksellen** [comment]
(or https://github.com/andrewgodwin/channels/)

**Comment by tiltec** [comment]
Ok, so I would not say that we merge frontend into backend anymore. Looks quite good so far!
But I would still merge socket into backend!
